#Apply the user's normal settings
[ -a ~/.bashrc ] && . ~/.bashrc

#Use barun history if present
[ -a ~/.barun_history ] && HISTFILE=~/.barun_history

#Set the name of window and prompt
PS1="\[\033]0;baRun\007\]\\$ "
unset PROMPT_COMMAND

export SUDO_ASKPASS="/usr/bin/X11/ssh-askpass"
alias sudo='sudo -A '

delayandclose() {
	echo
	echo "Program exited with status: $?"
	xttitle "baRun: $BASHPID [completed]"
	xwininfo -id $wid | grep -q 'Map State: IsViewable'
	if [ $? -ne 0 ]; then
		read -t 60 -n 1 -s || exit
	fi
	echo
	read -p "Press q to quit" -s -d q
	exit
}

background() {
	[[ -n $COMP_LINE ]] && return
        for pattern in ${ignore_patterns[@]}; do
	  [[ $BASH_COMMAND =~ $pattern || ${FUNCNAME[1]} =~ $pattern  ]] && return
	done

        history -a

	xttitle "baRun: $BASHPID"
	xdotool windowunmap $wid
	trap DEBUG

	PROMPT_COMMAND="delayandclose"
}

set -o functrace
shopt -s extdebug

wid=`xdotool getactivewindow`

[[ -f ~/.barun_ignore ]] && ignore_file=~/.barun_ignore || ignore_file=/etc/barun/ignore
readarray -t ignore_patterns < <(sed 's/#.*//' "$ignore_file" | grep -v '^$')

if [[ -n $baruncmd ]]; then
	echo "\$ $baruncmd"
	trap 'background' DEBUG
	"$baruncmd"
else
	trap 'background' DEBUG
fi
